### ISSUE TITLE
根据http://bbci.de/competition/iii/index.html链接下载的数据和您代码中的数据有些出入

### ISSUE THREAD

**Issue by zzyy17** [ZhangXiao96/Speller-Attacks#1]
```
signal = train_data['Signal']
stimuli = train_data['StimulusCode']
label = train_data['StimulusType']
char = train_data['TargetChar']
```
这部分的数据名貌似有些不一样，这是我修改之后的；
在运行数据的时候，出现了错误
`
Traceback (most recent call last):
  File "C:/Users/zhouy_g2r78zv/PycharmProjects/eegad/train.py", line 64, in <module>
    epochs, y = trials_to_epochs(signal, label, stimuli, epoch_length)
  File "C:\Users\zhouy_g2r78zv\PycharmProjects\eegad\lib\utils_P300Speller.py", line 114, in trials_to_epochs
    epochs = np.array(epochs).squeeze()
ValueError: could not broadcast input array from shape (7794,64) into shape (7794)
`

**Comment by ZhangXiao96** [comment]
Hi, it seems that there is a file for data preprocessing missing. I will re-upload it once I can go back to university.

**Comment by zzyy17** [comment]
Oh, I see.  Sorry to bother you again, is there any possible way that you could share me the preprocssing file or any thought that I can get the missing part, thank you very much and wish you all the best. We all love 武汉!!!

**Comment by zzyy17** [comment]
May I ask what is the version of Python compiler do you use?

**Comment by zzyy17** [comment]
Oh, another thing about the code, could this code ran on the CPU only??  I saw you used `NCHW` at `conv2d` method

**Comment by ZhangXiao96** [comment]
I suppose Python3.5+ would work. BTW, the version of tensorflow is very important (since many APIs have been changed through the update of tensorflow).
We only test this code on GPU. Maybe you should make some adaptions to the code if you want to run this code on CPU.

**Comment by ZhangXiao96** [comment]
Hi, I have uploaded the data preprocessing file. Please check the file [https://github.com/ZhangXiao96/Speller-Attacks/blob/master/P300_Speller/preprocess_data.py](https://github.com/ZhangXiao96/Speller-Attacks/blob/master/P300_Speller/preprocess_data.py). I will close this issue. If you have any other problems, please feel free to open a new issue!
