### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'targets'

### ISSUE THREAD

**Issue by elimii** [ZhangXiao96/Speller-Attacks#3]
hello, sorry to take your time again . When I run the file "generate-adversarail-template", I am getting the below error. could you please guide me?
  ....\lib\KerasAdversary.py", line 45, in __init__
    self.target_tensor = model.targets[0]
AttributeError: 'Model' object has no attribute 'targets'

Thanks

**Comment by elimii** [comment]
> hello, sorry to take your time again . When I run the file "generate-adversarail-template", I am getting the below error. could you please guide me?
> ....\lib\KerasAdversary.py", line 45, in **init**
> self.target_tensor = model.targets[0]
> AttributeError: 'Model' object has no attribute 'targets'
> 
> Thanks

Hi, I am still waiting for your answer , I would be really thankful, if you could tell me what is problem here? :)

**Comment by ZhangXiao96** [comment]
> > hello, sorry to take your time again . When I run the file "generate-adversarail-template", I am getting the below error. could you please guide me?
> > ....\lib\KerasAdversary.py", line 45, in **init**
> > self.target_tensor = model.targets[0]
> > AttributeError: 'Model' object has no attribute 'targets'
> > Thanks
> 
> Hi, I am still waiting for your answer , I would be really thankful, if you could tell me what is problem here? :)

I'm very busy in recent times and sorry about the late reply. I guess the issue is caused by the version of Tensorflow. I suggest building an environment that includes the same version of Tensorflow I list, since Tensorflow always update its base functions and parameters.

**Comment by elimii** [comment]
> > > hello, sorry to take your time again . When I run the file "generate-adversarail-template", I am getting the below error. could you please guide me?
> > > ....\lib\KerasAdversary.py", line 45, in **init**
> > > self.target_tensor = model.targets[0]
> > > AttributeError: 'Model' object has no attribute 'targets'
> > > Thanks
> > 
> > 
> > Hi, I am still waiting for your answer , I would be really thankful, if you could tell me what is problem here? :)
> 
> I'm very busy in recent times and sorry about the late reply. I guess the issue is caused by the version of Tensorflow. I suggest building an environment that includes the same version of Tensorflow I list, since Tensorflow always update its base functions and parameters.

Thank you so much for your reply.  yes the problem was version of tensorflow. I have already changed it and it works well.  best luck :)
